"""init_schema

Revision ID: 8a3295d8fe99
Revises: 
Create Date: 2026-05-14 20:37:57.339738+00:00
"""

from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import pgvector.sqlalchemy

# revision identifiers, used by Alembic.
revision: str = '8a3295d8fe99'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute("CREATE EXTENSION IF NOT EXISTS vector;")
    """Apply this migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_chunks',
    sa.Column('id', sa.UUID(), nullable=False, comment='Chunk primary key (UUID v4)'),
    sa.Column('doc_id', sa.String(length=255), nullable=False, comment='Parent document identifier'),
    sa.Column('source_name', sa.String(length=512), nullable=False, comment='Original filename shown in citations'),
    sa.Column('chunk_index', sa.Integer(), nullable=False, comment='Zero-based chunk position within the document'),
    sa.Column('content', sa.Text(), nullable=False, comment='Raw text of the chunk'),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=True, comment='384-dim dense vector from BAAI/bge-small-en-v1.5'),
    sa.Column('fts_vector', postgresql.TSVECTOR(), nullable=True, comment='PostgreSQL tsvector for GIN full-text search'),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Extensible JSON metadata (page, section, …)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_doc_chunks_embedding', 'document_chunks', ['embedding'], unique=False, postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.create_index('ix_doc_chunks_fts', 'document_chunks', ['fts_vector'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_document_chunks_doc_id'), 'document_chunks', ['doc_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert this migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_document_chunks_doc_id'), table_name='document_chunks')
    op.drop_index('ix_doc_chunks_fts', table_name='document_chunks', postgresql_using='gin')
    op.drop_index('ix_doc_chunks_embedding', table_name='document_chunks', postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.drop_table('document_chunks')
    # ### end Alembic commands ###
